-- TigerRAG PostgreSQL 初始化脚本。
-- 本脚本由维护人员手工执行，不依赖 EF Core Migration。

BEGIN;

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "KnowledgeBases" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" text,
    "OwnerId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_KnowledgeBases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_KnowledgeBases_AspNetUsers_OwnerId"
        FOREIGN KEY ("OwnerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Documents" (
    "Id" uuid NOT NULL,
    "KnowledgeBaseId" uuid NOT NULL,
    "FileName" character varying(500) NOT NULL,
    "StoragePath" character varying(1000) NOT NULL,
    "Status" character varying(32) NOT NULL,
    "ChunkCount" integer NOT NULL,
    "FailureReason" text,
    "CreatedBy" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_AspNetUsers_CreatedBy"
        FOREIGN KEY ("CreatedBy") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Documents_KnowledgeBases_KnowledgeBaseId"
        FOREIGN KEY ("KnowledgeBaseId") REFERENCES "KnowledgeBases" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DocumentChunks" (
    "Id" uuid NOT NULL,
    "DocumentId" uuid NOT NULL,
    "Position" integer NOT NULL,
    "PageNumber" integer,
    "Title" text,
    "Content" text NOT NULL,
    "SearchVector" tsvector,
    CONSTRAINT "PK_DocumentChunks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentChunks_Documents_DocumentId"
        FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DocumentPermissions" (
    "DocumentId" uuid NOT NULL,
    "PrincipalType" character varying(16) NOT NULL,
    "PrincipalId" uuid NOT NULL,
    CONSTRAINT "PK_DocumentPermissions" PRIMARY KEY ("DocumentId", "PrincipalType", "PrincipalId"),
    CONSTRAINT "FK_DocumentPermissions_Documents_DocumentId"
        FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Conversations" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Title" character varying(300) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastMessageAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Conversations_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Messages" (
    "Id" uuid NOT NULL,
    "ConversationId" uuid NOT NULL,
    "Role" character varying(32) NOT NULL,
    "Content" text NOT NULL,
    "TokenCount" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Conversations_ConversationId"
        FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AuditLogs" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Query" text NOT NULL,
    "RetrievedDocumentIds" uuid[] NOT NULL,
    "Answer" text,
    "IpAddress" character varying(64),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuditLogs_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" character varying(64) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES
    ('1f0187a1-2897-4bf8-ab73-27fa1a2e4c76', '1f0187a1-2897-4bf8-ab73-27fa1a2e4c76', 'KbManager', 'KBMANAGER'),
    ('8f86fa4c-c8e5-4bc0-a563-528b70a74576', '8f86fa4c-c8e5-4bc0-a563-528b70a74576', 'Admin', 'ADMIN'),
    ('9081bc7b-1762-43cf-8649-bc30ed21ec52', '9081bc7b-1762-43cf-8649-bc30ed21ec52', 'Auditor', 'AUDITOR'),
    ('cb81efa4-2203-4f2b-88e4-1e18af3ba95c', 'cb81efa4-2203-4f2b-88e4-1e18af3ba95c', 'Editor', 'EDITOR'),
    ('eadf72f7-d444-43cc-9fd9-5aa320640274', 'eadf72f7-d444-43cc-9fd9-5aa320640274', 'Viewer', 'VIEWER')
ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Conversations_UserId" ON "Conversations" ("UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_DocumentChunks_DocumentId_Position"
    ON "DocumentChunks" ("DocumentId", "Position");
CREATE INDEX IF NOT EXISTS "IX_DocumentChunks_SearchVector"
    ON "DocumentChunks" USING GIN ("SearchVector");
CREATE INDEX IF NOT EXISTS "IX_DocumentPermissions_PrincipalType_PrincipalId"
    ON "DocumentPermissions" ("PrincipalType", "PrincipalId");
CREATE INDEX IF NOT EXISTS "IX_Documents_CreatedBy" ON "Documents" ("CreatedBy");
CREATE INDEX IF NOT EXISTS "IX_Documents_KnowledgeBaseId_Status"
    ON "Documents" ("KnowledgeBaseId", "Status");
CREATE INDEX IF NOT EXISTS "IX_KnowledgeBases_OwnerId" ON "KnowledgeBases" ("OwnerId");
CREATE INDEX IF NOT EXISTS "IX_Messages_ConversationId_CreatedAt"
    ON "Messages" ("ConversationId", "CreatedAt");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId_RevokedAt"
    ON "RefreshTokens" ("UserId", "RevokedAt");

COMMIT;
